ALTER TABLE  `#__jg_individuals` ADD `created_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER published;
ALTER TABLE  `#__jg_individuals` ADD `created_by` INT(11) NOT NULL DEFAULT '0' AFTER created_date;
ALTER TABLE  `#__jg_individuals` ADD `modified_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER created_by;
ALTER TABLE  `#__jg_individuals` ADD `modified_by` INT(11) NOT NULL DEFAULT '0' AFTER modified_date;
ALTER TABLE  `#__jg_individuals` ADD `vendor_id` INT(11) NOT NULL DEFAULT '0' AFTER modified_by;
ALTER TABLE  `#__jg_organizations` ADD `created_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER published;
ALTER TABLE  `#__jg_organizations` ADD `created_by` INT(11) NOT NULL DEFAULT '0' AFTER created_date;
ALTER TABLE  `#__jg_organizations` ADD `modified_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER created_by;
ALTER TABLE  `#__jg_organizations` ADD `modified_by` INT(11) NOT NULL DEFAULT '0' AFTER modified_date;
ALTER TABLE  `#__jg_organizations` ADD `vendor_id` INT(11) NOT NULL DEFAULT '0' AFTER modified_by;
ALTER TABLE #__jg_campaigns ADD INDEX vendor_id_idx (vendor_id);
ALTER TABLE #__jg_campaigns_givebacks ADD INDEX campaign_id_idx (campaign_id);
ALTER TABLE #__jg_donors ADD INDEX campaign_id_idx (campaign_id);
ALTER TABLE #__jg_donors ADD INDEX contributor_id_idx (contributor_id);
ALTER TABLE #__jg_donors ADD INDEX user_id_idx (user_id);
ALTER TABLE #__jg_donations ADD INDEX campaign_id_idx (campaign_id);
ALTER TABLE #__jg_donations ADD INDEX donor_id_idx (donor_id);
ALTER TABLE #__jg_donations ADD INDEX giveback_id_idx (giveback_id);
ALTER TABLE #__jg_orders ADD INDEX campaign_id_idx (campaign_id);
ALTER TABLE #__jg_orders ADD INDEX donor_id_idx (donor_id);
ALTER TABLE #__jg_orders ADD INDEX donation_id_idx (donation_id);
ALTER TABLE #__jg_reports ADD INDEX campaign_id_idx (campaign_id);
ALTER TABLE #__jg_individuals ADD INDEX vendor_id_idx (vendor_id);
ALTER TABLE #__jg_organizations ADD INDEX vendor_id_idx (vendor_id);
ALTER TABLE #__jg_organization_contacts ADD INDEX organization_id_idx (organization_id);
ALTER TABLE #__jg_organization_contacts ADD INDEX individual_id_idx (individual_id);
