ALTER TABLE `#__jg_campaigns` CHANGE `category_id` `category_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns` CHANGE `vendor_id` `vendor_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns` CHANGE `org_ind_type` `org_ind_type` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_campaigns` CHANGE `creator_id` `creator_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns` CHANGE `title` `title` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_campaigns` CHANGE `alias` `alias` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_campaigns` CHANGE `goal_amount` `goal_amount` DECIMAL(16,5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns` CHANGE `group_name` `group_name` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_campaigns` CHANGE `allow_exceed` `allow_exceed` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns` CHANGE `allow_view_donations` `allow_view_donations` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns` CHANGE `js_groupid` `js_groupid` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns` CHANGE `short_description` `short_description` text DEFAULT NULL;
ALTER TABLE `#__jg_campaigns` CHANGE `long_description` `long_description` text DEFAULT NULL;
ALTER TABLE `#__jg_campaigns` CHANGE `internal_use` `internal_use` text DEFAULT NULL COMMENT 'use internally';
ALTER TABLE `#__jg_campaigns` CHANGE `meta_data` `meta_data` text DEFAULT NULL;
ALTER TABLE `#__jg_campaigns` CHANGE `meta_desc` `meta_desc` text DEFAULT NULL;
ALTER TABLE `#__jg_campaigns` CHANGE `created` `created` datetime DEFAULT NULL;
ALTER TABLE `#__jg_campaigns` CHANGE `modified` `modified` datetime DEFAULT NULL;
ALTER TABLE `#__jg_campaigns` CHANGE `start_date` `start_date` datetime DEFAULT NULL;
ALTER TABLE `#__jg_campaigns` CHANGE `end_date` `end_date` datetime DEFAULT NULL;

ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `campaign_id` `campaign_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `title` `title` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `amount` `amount` DECIMAL(16,5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `order` `order` int(5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `quantity` `quantity` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `total_quantity` `total_quantity` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `image_path` `image_path` varchar(400) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_campaigns_givebacks` CHANGE `description` `description` text DEFAULT NULL COMMENT 'giveback details';

ALTER TABLE `#__jg_donations` CHANGE `campaign_id` `campaign_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table #__jg_campaigns';
ALTER TABLE `#__jg_donations` CHANGE `donor_id` `donor_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table #__jg_donors';
ALTER TABLE `#__jg_donations` CHANGE `order_id` `order_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table #__jg_orders';
ALTER TABLE `#__jg_donations` CHANGE `giveback_id` `giveback_id` int(11) NOT NULL DEFAULT 0 COMMENT 'id of jg_campaigns_givebacks';
ALTER TABLE `#__jg_donations` CHANGE `annonymous_donation` `annonymous_donation` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_donations` CHANGE `comment` `comment` text DEFAULT NULL;

ALTER TABLE `#__jg_donors` CHANGE `user_id` `user_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table #__users';
ALTER TABLE `#__jg_donors` CHANGE `contributor_id` `contributor_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table #__individuals or #__organizations';
ALTER TABLE `#__jg_donors` CHANGE `donor_type` `donor_type` varchar(20) NOT NULL DEFAULT '' COMMENT 'Type of donor';
ALTER TABLE `#__jg_donors` CHANGE `campaign_id` `campaign_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table #__jg_donors';
ALTER TABLE `#__jg_donors` CHANGE `email` `email` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `first_name` `first_name` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `last_name` `last_name` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `org_name` `org_name` varchar(250) NOT NULL DEFAULT '' COMMENT 'Organization name';
ALTER TABLE `#__jg_donors` CHANGE `city` `city` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `state` `state` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `country` `country` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `zip` `zip` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `phone` `phone` varchar(50) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `taxnumber` `taxnumber` varchar(50) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_donors` CHANGE `address` `address` text DEFAULT NULL;
ALTER TABLE `#__jg_donors` CHANGE `address2` `address2` text DEFAULT NULL;

ALTER TABLE `#__jg_orders` CHANGE `order_id` `order_id` VARCHAR( 23 ) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_orders` CHANGE `campaign_id` `campaign_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table#__jg_campaigns';
ALTER TABLE `#__jg_orders` CHANGE `donor_id` `donor_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table#__jg_donors';
ALTER TABLE `#__jg_orders` CHANGE `donation_id` `donation_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table#__jg_donations';
ALTER TABLE `#__jg_orders` CHANGE `fund_holder` `fund_holder` tinyint( 1 ) NOT NULL DEFAULT 0 COMMENT 'To whose account money was originally transferred to: 0-admin, 1-campaign promoter';
ALTER TABLE `#__jg_orders` CHANGE `transaction_id` `transaction_id` varchar(100) NOT NULL DEFAULT '' COMMENT 'transaction id given by payment processor';
ALTER TABLE `#__jg_orders` CHANGE `original_amount` `original_amount` DECIMAL(16,5) NOT NULL DEFAULT 0 COMMENT 'original amount with no fee applied';
ALTER TABLE `#__jg_orders` CHANGE `amount` `amount` DECIMAL(16,5) NOT NULL DEFAULT 0 COMMENT 'amount after applying fee';
ALTER TABLE `#__jg_orders` CHANGE `fee` `fee` DECIMAL(16,5) NOT NULL DEFAULT 0 COMMENT 'processing fee';
ALTER TABLE `#__jg_orders` CHANGE `vat_number` `vat_number` varchar(100) NOT NULL DEFAULT '' COMMENT 'VAT number';
ALTER TABLE `#__jg_orders` CHANGE `status` `status` varchar(100) NOT NULL DEFAULT '' COMMENT 'payment status';
ALTER TABLE `#__jg_orders` CHANGE `processor` `processor` varchar(100) NOT NULL DEFAULT '' COMMENT 'payment gateway used';
ALTER TABLE `#__jg_orders` CHANGE `ip_address` `ip_address` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP address of payer';
ALTER TABLE `#__jg_orders` CHANGE `cdate` `cdate` datetime DEFAULT NULL COMMENT 'creation date';
ALTER TABLE `#__jg_orders` CHANGE `mdate` `mdate` datetime DEFAULT NULL COMMENT 'modification date';
ALTER TABLE `#__jg_orders` CHANGE `payment_received_date` `payment_received_date` datetime DEFAULT NULL COMMENT 'Donation received date';
ALTER TABLE `#__jg_orders` CHANGE `extra` `extra` text DEFAULT NULL;
ALTER TABLE `#__jg_orders` CHANGE `params` `params` text DEFAULT NULL;

ALTER TABLE `#__tj_media_files` CHANGE `title` `title` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `type` `type` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `path` `path` varchar(250) COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `state` `state` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `source` `source` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `original_filename` `original_filename` varchar(250) COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `size` `size` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `storage` `storage` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `created_by` `created_by` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `access` `access` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `created_date` `created_date` datetime DEFAULT NULL;
ALTER TABLE `#__tj_media_files` CHANGE `params` `params` text DEFAULT NULL;

ALTER TABLE `#__tj_media_files_xref` CHANGE `media_id` `media_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files_xref` CHANGE `client_id` `client_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files_xref` CHANGE `client` `client` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files_xref` CHANGE `is_gallery` `is_gallery` tinyint(1) NOT NULL DEFAULT 0;

ALTER TABLE `#__jg_reports` CHANGE `campaign_id` `campaign_id` int(5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_reports` CHANGE `title` `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `#__jg_reports` CHANGE `status` `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'published =1, unpublished = 0';
ALTER TABLE `#__jg_reports` CHANGE `created_by` `created_by` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'created by user id';
ALTER TABLE `#__jg_reports` CHANGE `created_on` `created_on` datetime DEFAULT NULL;
ALTER TABLE `#__jg_reports` CHANGE `modified_on` `modified_on` datetime DEFAULT NULL;
ALTER TABLE `#__jg_reports` CHANGE `description` `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL;

ALTER TABLE `#__jg_individuals` CHANGE `first_name` `first_name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_individuals` CHANGE `last_name` `last_name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_individuals` CHANGE `email` `email` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_individuals` CHANGE `phone` `phone` varchar(20) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_individuals` CHANGE `taxnumber` `taxnumber` varchar(50) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_individuals` CHANGE `user_id` `user_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_individuals` CHANGE `country` `country` int(3) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_individuals` CHANGE `region` `region` int(5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_individuals` CHANGE `city` `city` int(5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_individuals` CHANGE `other_city_check` `other_city_check` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_individuals` CHANGE `other_city_value` `other_city_value` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_individuals` CHANGE `zip` `zip` varchar(30) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_individuals` CHANGE `published` `published` tinyint(3) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_individuals` CHANGE `created_date` `created_date` datetime DEFAULT NULL;
ALTER TABLE `#__jg_individuals` CHANGE `modified_date` `modified_date` datetime DEFAULT NULL;
ALTER TABLE `#__jg_individuals` CHANGE `addr_line_1` `addr_line_1` text DEFAULT NULL;
ALTER TABLE `#__jg_individuals` CHANGE `addr_line_2` `addr_line_2` text DEFAULT NULL;

ALTER TABLE `#__jg_organizations` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_organizations` CHANGE `email` `email` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_organizations` CHANGE `phone` `phone` varchar(20) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_organizations` CHANGE `taxnumber` `taxnumber` varchar(50) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_organizations` CHANGE `website` `website` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_organizations` CHANGE `user_id` `user_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_organizations` CHANGE `country` `country` int(3) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_organizations` CHANGE `region` `region` int(5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_organizations` CHANGE `city` `city` int(5) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_organizations` CHANGE `other_city_check` `other_city_check` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_organizations` CHANGE `other_city_value` `other_city_value` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_organizations` CHANGE `zip` `zip` varchar(30) NOT NULL DEFAULT '';
ALTER TABLE `#__jg_organizations` CHANGE `published` `published` tinyint(3) NOT NULL DEFAULT 0;
ALTER TABLE `#__jg_organizations` CHANGE `created_date` `created_date` datetime DEFAULT NULL;
ALTER TABLE `#__jg_organizations` CHANGE `modified_date` `modified_date` datetime DEFAULT NULL;
ALTER TABLE `#__jg_organizations` CHANGE `addr_line_1` `addr_line_1` text DEFAULT NULL;
ALTER TABLE `#__jg_organizations` CHANGE `addr_line_2` `addr_line_2` text DEFAULT NULL;

ALTER TABLE `#__jg_organization_contacts` CHANGE `organization_id` `organization_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table#__jg_organizations';
ALTER TABLE `#__jg_organization_contacts` CHANGE `individual_id` `individual_id` int(11) NOT NULL DEFAULT 0 COMMENT 'fk - primary key of table#__jg_individuals';
